"""Realtime WebSocket channel."""

from app.realtime.auth import (
    ACCESS_TOKEN_SUBPROTOCOL_PREFIX,
    BEARER_SUBPROTOCOL,
    extract_access_token,
    select_subprotocol,
)
from app.realtime.gateway import RealtimeGateway, create_realtime_router
from app.realtime.schemas import (
    FrameRejected,
    InboundMessage,
    ParsedFrame,
    PingMessage,
    SubscribeMessage,
    UnsubscribeMessage,
    decode_inbound_frame,
    parse_inbound_message,
    read_inbound_frame,
)
from app.realtime.topics import (
    MAX_TOPIC_LENGTH,
    REALTIME_COLLECTION_TOPICS,
    REALTIME_ENTITY_TYPES,
    REALTIME_TOPIC_DEALS,
    REALTIME_TOPIC_ORDERS,
    ParsedRealtimeTopic,
    TopicPermissionRequirement,
    collection_topic_for_entity,
    deal_topic,
    deals_topic,
    entity_topic,
    is_realtime_topic,
    order_topic,
    orders_topic,
    parse_realtime_topic,
    topic_permission_requirement,
)
from app.realtime.types import (
    CLOSE_CODE_GOING_AWAY,
    AuthContextLike,
    CanSubscribe,
    RealtimeErrorCode,
    RealtimeGatewayOptions,
    RealtimeGatewayStats,
    RealtimeSocketLike,
    VerifyAccessToken,
)

__all__ = [
    "ACCESS_TOKEN_SUBPROTOCOL_PREFIX",
    "BEARER_SUBPROTOCOL",
    "CLOSE_CODE_GOING_AWAY",
    "MAX_TOPIC_LENGTH",
    "REALTIME_COLLECTION_TOPICS",
    "REALTIME_ENTITY_TYPES",
    "REALTIME_TOPIC_DEALS",
    "REALTIME_TOPIC_ORDERS",
    "AuthContextLike",
    "CanSubscribe",
    "FrameRejected",
    "InboundMessage",
    "ParsedFrame",
    "ParsedRealtimeTopic",
    "PingMessage",
    "RealtimeErrorCode",
    "RealtimeGateway",
    "RealtimeGatewayOptions",
    "RealtimeGatewayStats",
    "RealtimeSocketLike",
    "SubscribeMessage",
    "TopicPermissionRequirement",
    "UnsubscribeMessage",
    "VerifyAccessToken",
    "collection_topic_for_entity",
    "create_realtime_router",
    "deal_topic",
    "deals_topic",
    "decode_inbound_frame",
    "entity_topic",
    "extract_access_token",
    "is_realtime_topic",
    "order_topic",
    "orders_topic",
    "parse_inbound_message",
    "parse_realtime_topic",
    "read_inbound_frame",
    "select_subprotocol",
    "topic_permission_requirement",
]
